### ISSUE TITLE
How to use with Webpack?

### ISSUE THREAD

**Issue by IPWright83** [etiennecrb/d3-xyzoom#2]
I can't work out how to import this into an existing ES6 project using webpack. Could you provide an example? The nearest I've got so far is:

```
import * as d3 from "d3";
import { xyzoom } from "d3-xyzoom"
```

however when doing this I encounter this error https://github.com/d3/d3-zoom/issues/27 .

**Comment by etiennecrb** [comment]
Unfortunately, I don't use this plugin with a Webpack configuration.
However, [this webpack plugin](https://www.npmjs.com/package/d3-webpack-loader) might be a good start to find a solution.

**Comment by IPWright83** [comment]
@etiennecrb thanks! I'll take a look at that and see if it solves my problem.

**Comment by nothingalike** [comment]
so i just wanted to make a note about this particular situation. I'm using D3 v5 and webpack. The way i got it working was import D3 and this package as normal.
`import * as d3 from "d3";`
`import * as d3xyzoom from "d3-xyzoom";`

Now d3-xyzoom is using independently of my normal D3 modules, but works as expected just fine. 

`
//example code`
`let xy = d3xyzoom.xyzoomTransform(this.some-selection.node())
`

**Comment by Rufflet** [comment]
**One more note.**
To import _d3-xyzoom_ as d3 module I used these lines:

```
import * as d3 from "d3";
import * as d3xyzoom from "d3-xyzoom";
Object.assign(d3, d3xyzoom);
```

This way it will work like in examples.

`const zoom = d3.xyzoom()`
