### ISSUE TITLE
Using d3-xyzoom click events are swallowed

### ISSUE THREAD

**Issue by IPWright83** [etiennecrb/d3-xyzoom#3]
If you use `d3-xyzoom` in the usual way then it swallows click events, unlike `d3-zoom`. Here's a codepen illustrating the effect: https://codepen.io/IPWright83/pen/RLgKer?editors=1011

Copy of the code I'm using to reproduce this issue. Clicking on the circle won't trigger the clicked event:

```
const zoom = d3
  .xyzoom()
  .extent([[0, 0], [250, 250]])
  .scaleExtent([0.5, 10])
  .on("zoom", () => {
    d3.select(target)
      .select("g")
      .attr("transform", d3.event.transform);
  });

  d3.select(target).call(zoom);

  d3.select(target)
    .select("circle")
    .on("click", () => {
    alert("clicked d3-xyzoom");
  });
```

**Comment by etiennecrb** [comment]
Your codepen is working for me on Chrome 61 and Firefox 55... What is your configuration?

**Comment by IPWright83** [comment]
@etiennecrb that's really interesting... it also works from my home PC. I'll check my work laptop on Monday and confirm the build of Chrome.

**Comment by IPWright83** [comment]
I'm also using Chrome 61, I've got a colleague to check it and interestingly it works intermittently (fun!). I've had it reliably working, and reliably not working in two different browser windows at the same time.

I'm currently trying to debug it, although at the moment I can't identify what's causing the issue. It seems that the event is caught by Chrome correctly as a `MouseEvent` fired on an `svg:circle` but by the time it gets to `d3` firing the event, it's changing what `this` is between the `svg:circle` and the `window` object. Which would obviously explain why the alert doesn't trigger.

At the moment it always reliably works using the standard `d3-zoom` so I'm not yet sure why the event is being fired against the `window` rather than the `svg:circle`. Thought I'd add my progress on here in case you can point me to anything that might be relevant.

**Comment by etiennecrb** [comment]
Ok, thank you. We should also compared d3-xyzoom with d3-zoom source code because I forked it last year and I haven't implemented the patches & bug fixes that might have been done for d3-zoom.

**Comment by IPWright83** [comment]
Exactly what I'm doing right now, something I've noticed in the `mousemoved` listener within `d3-xyzoom` is this:

```
function mousemoved() {
      noevent();
      if (!g.moved) {
        var dx = event.clientX - x0, dy = event.clientY - y0;
        g.moved = dx * dx + dy * dy > clickDistance2;
      }
      g.zoom("mouse", constrain(translate(g.that.__zoom, g.mouse[0] = mouse(g.that), g.mouse[1]), g.extent));
    }
```

So it's allowing a small movement threshold, and anything below that threshold is going to trigger a `click` rather than a `drag`. I would imagine that's the missing bit. What would you suggest is the easiest way to patch up to latest? I'm thinking probably pull `d3-xyzoom` and re-apply your changes?

**Comment by etiennecrb** [comment]
I think it might be easier to go through all commits of d3-zoom since Dec. 2016 (there are only about 15 relevant commits) and apply them in d3-xyzoom.

You can do it if you're interested.
It can be done in several PR so if the ["phantom gesture" issue](https://github.com/d3/d3-zoom/commit/3531fd54820e3812c9a70071cd5077f1d92b56e1) is an urgent one for you, you can begin with this change!

**Comment by IPWright83** [comment]
Sure - I'm on it. Have a PR shortly all being well.

**Comment by IPWright83** [comment]
@etiennecrb just to confirm that it all looks fixed. Thanks for the quick merge
