### ISSUE TITLE
Zoom for separate axes?

### ISSUE THREAD

**Issue by aldanor** [etiennecrb/d3-xyzoom#5]
I was trying to figure out if it was possible to do something like this with d3-xyzoom:

http://bl.ocks.org/jgbos/9752277

Basically, to have a 'normal' zoom, plus separate x/y zoom handlers for separate axes, and combine it all together.

Would appreciate any help, thanks!

**Comment by aldanor** [comment]
@etiennecrb Really hoping you would know :)

I've tried creating three separate d3-xyzoom objects (for the central piece and for both scales), and I figure they should then communicate/synchronize the translation between each other and the nodes, but I can't seem to figure the exact way to do it...

**Comment by aldanor** [comment]
Actually... after one more day of trial & error, here it is (try zooming in and then panning around, on either of the coloured rectangles):

https://codepen.io/aldanor/pen/WabmoL

Unless I've missed something important, it seems to work fine so far (would still appreciate any comments might you have any, though...). Apologies for the hassle :)

**Comment by etiennecrb** [comment]
Your code seems good to me :wink: 
Zooms are always very difficult to reason about... What is difficult now compared to your example (which is in d3 v3) is that zoom transform is no longer stored in the "behavior" but on the `rect` on which is it applied. Thus, the synchronization step is needed.
